{
    "name": "LightLink Shopify 多站点运营中台",
    "version": "19.0.1.1.0",
    "summary": "在一个 Odoo 数据库内管理多个 Shopify 店铺的商品、分类、库存、订单、履约、询盘和同步异常",
    "category": "Sales/Sales",
    "author": "LightLink",
    "license": "LGPL-3",
    "depends": [
        "product_social_content_bridge",
        "mail",
        "crm",
        "sale_management",
        "sale_stock",
        "stock",
        "website",
    ],
    "data": [
        "security/shopify_security.xml",
        "security/ir.model.access.csv",
        "data/shopify_cron.xml",
        "views/shopify_store_views.xml",
        "views/shopify_catalog_views.xml",
        "views/shopify_job_views.xml",
        "views/shopify_order_views.xml",
        "views/product_template_views.xml",
        "wizard/shopify_publish_wizard_views.xml",
        "views/shopify_dashboard_views.xml",
        "views/shopify_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "lightlink_shopify_multistore/static/src/js/shopify_dashboard.js",
            "lightlink_shopify_multistore/static/src/js/product_workspace_patch.js",
            "lightlink_shopify_multistore/static/src/xml/shopify_dashboard.xml",
            "lightlink_shopify_multistore/static/src/xml/product_workspace_patch.xml",
            "lightlink_shopify_multistore/static/src/scss/shopify_dashboard.scss",
        ],
    },
    "application": True,
    "installable": True,
}
