{
    "name": "LightLink 采购服务官网",
    "version": "19.0.2.5.1",
    "summary": "独立多语言采购服务官网、内容资产与结构化询盘运营闭环",
    "category": "Website/Website",
    "author": "LightLink",
    "license": "LGPL-3",
    "depends": [
        "website",
        "website_blog",
        "website_sale",
        "crm",
        "product_social_content_bridge",
        "OdooTranslate",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/sourcing_defaults.xml",
        "data/sourcing_content_expansion.xml",
        "data/sourcing_product_categories.xml",
        "data/sourcing_trust_content.xml",
        "data/sourcing_yiwu_content.xml",
        "views/sourcing_backend_views.xml",
        "views/website_operations_views.xml",
        "views/sourcing_website_templates.xml",
        "views/sourcing_website_menus.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "lightlink_sourcing_website/static/src/scss/sourcing_website.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "application": False,
    "installable": True,
}
