{
    "name": "产品智能中心",
    "version": "19.0.1.43.1",
    "summary": "采集、评分、审核并转化产品机会",
    "category": "Sales",
    "author": "LightLink",
    "license": "LGPL-3",
    "depends": ["base_setup", "mail", "product", "website_sale", "OdooTranslate"],
    "data": [
        "security/product_intelligence_security.xml",
        "security/ir.model.access.csv",
        "data/product_intelligence_cron.xml",
        "data/odoo_translate_fields.xml",
        "wizard/product_intelligence_token_wizard_views.xml",
        "wizard/product_intelligence_sourcing_role_wizard_views.xml",
        "views/product_intelligence_source_views.xml",
        "views/product_intelligence_sourcing_views.xml",
        "views/product_intelligence_candidate_views.xml",
        "views/product_template_views.xml",
        "views/website_product_details_templates.xml",
        "views/res_config_settings_views.xml",
        "views/product_intelligence_menus.xml",
    ],
    "application": True,
    "installable": True,
}
