{
    "name": "产品线社媒发布中心",
    "version": "19.0.8.0.1",
    "summary": "从赛道、产品池到ChatGPT协同、销售归因和持续优化的市场运营中心",
    "category": "Marketing/Social Marketing",
    "author": "LightLink",
    "license": "LGPL-3",
    "depends": ["product_intelligence_hub", "social", "crm", "sale_crm", "website_sale", "purchase", "stock"],
    "data": [
        "security/ai_security.xml",
        "security/ir.model.access.csv",
        "data/media_models.xml",
        "data/market_operation_templates.xml",
        "data/content_strategy_templates.xml",
        "data/ai_blueprints.xml",
        "data/ai_cron.xml",
        "views/social_content_views.xml",
        "views/crm_lead_views.xml",
        "views/social_publishing_views.xml",
        "views/account_registration_views.xml",
        "views/publishing_delivery_views.xml",
        "views/market_operation_views.xml",
        "views/business_hub_views.xml",
        "views/social_content_menus.xml",
        "views/ai_operations_views.xml",
        "views/res_config_settings_views.xml",
        "views/local_production_views.xml",
        "views/app_menu_categories.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "product_social_content_bridge/static/src/js/business_navigation.js",
            "product_social_content_bridge/static/src/xml/business_navigation.xml",
            "product_social_content_bridge/static/src/scss/business_navigation.scss",
        ],
    },
    "uninstall_hook": "uninstall_hook",
    "application": True,
    "installable": True,
}
